"""Checklist model — MRP-generated tasks for the dynamic checklist."""

import enum
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Enum, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class ChecklistPriority(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    INFO = "INFO"


class ChecklistActionType(str, enum.Enum):
    NAVIGATE = "NAVIGATE"
    CREATE_PO = "CREATE_PO"
    CREATE_OFFER = "CREATE_OFFER"
    SEND_REMINDER = "SEND_REMINDER"
    OPEN_MODAL = "OPEN_MODAL"


class ChecklistTask(Base):
    """A task generated by the MRP engine for the admin's daily checklist."""

    __tablename__ = "checklist_tasks"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    priority: Mapped[ChecklistPriority] = mapped_column(
        Enum(ChecklistPriority, name="checklist_priority", native_enum=False),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    action_type: Mapped[ChecklistActionType] = mapped_column(
        Enum(ChecklistActionType, name="checklist_action_type", native_enum=False),
        nullable=False,
    )
    action_payload: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON string
    completed: Mapped[bool] = mapped_column(default=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<ChecklistTask id={self.id} title={self.title!r} done={self.completed}>"
